unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Install dein.vim
let s:cache_home= expand('~/.cache')
let s:dein_dir= s:cache_home . '/dein'
let s:dein_repo_dir= s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if !isdirectory(s:dein_repo_dir)
    call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
endif
let &runtimepath = s:dein_repo_dir . "," . &runtimepath

" Load plugins by dein
let s:toml_file = fnamemodify(expand('<sfile>'), ':h') . '/dein/dein.toml'
if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)
    call dein#load_toml(s:toml_file)
    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable
if has('vim_starting') && dein#check_install()
   call dein#install()
endif



" Setting statusline
set laststatus=2
let &statusline = "%<%f %m%r%h%w[%{&ff}][%{(&fenc!=''?&fenc:&enc).(&bomb?':bom':'')}] "
let &statusline .= "0x%B"
let &statusline .= "%=%l,%c%V %P"

set scrolloff=0
set mouse=
