unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Install dein.vim
let s:cache_home= expand('~/.cache')
let s:dein_dir= s:cache_home . '/dein'
let s:dein_repo_dir= s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if !isdirectory(s:dein_repo_dir)
    call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
endif
let &runtimepath = s:dein_repo_dir . "," . &runtimepath



set scrolloff=0
set mouse=
